# This docker compose will only be used by frontend developers since it isolates the database by the API interfaces
# Ports:
# - API -> 127.0.0.1:5000

version: "3.3"

networks:
  spainews:
    external: false

services:
  redis:
    networks:
      - spainews
    container_name: spainews-redis
    image: redis:latest
    restart: unless-stopped
  mongo:
    container_name: spainews-mongo
    image: mongo:latest
    restart: unless-stopped
    networks:
      - spainews
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: spainews
    volumes:
      - type: bind
        source: ./mongo-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
      - ./mongo-data:/data
  mariadb:
    networks:
      - spainews
    container_name: spainnews-mariadb
    restart: unless-stopped
    image: mariadb:latest
    volumes:
      - type: bind
        source: ./mariadb-init.d
        target: /docker-entrypoint-initdb.d
        read_only: true
      - ./mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: spainews
      MARIADB_DATABASE: spainews
      MARIADB_USER: spainews
      MARIADB_PASSWORD: spainews
  smtp:
    networks:
      - spainews
    container_name: spainews-mailhog
    restart: unless-stopped
    image: mailhog/mailhog
  test-data:
    restart: on-failure
    networks:
      - spainews
    container_name: spainews-test-data
    build:
      context: .
      dockerfile: test-data.Dockerfile
    volumes:
      - type: bind
        source: ./test-data
        target: /test-data
        read_only: true
  builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /spAInews/api
        read_only: true
      - type: bind
        source: ./build
        target: /build
  api:
    depends_on:
      - test-data
      - smtp
      - builder
      - redis
      - mariadb
      - mongo
    user: "api:api"
    container_name: spainews-api
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - type: bind
        source: ./build
        target: /build
        read_only: true
      - type: bind
        source: ./configs
        target: /configs
        read_only: true
    restart: unless-stopped
    networks:
      - spainews
    ports:
      - "127.0.0.1:5000:5000"