openapi: 3.0.3

components:
  securitySchemes:
    session-key:
      type: apiKey
      in: header
      name: Session
    basicAuth:
      type: http
      scheme: basic
  schemas:
    error-message:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      example:
        code: 1
        message: error message
  responses:
    server-error:
      description: Server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error-message"


info:
  title: SPAINEWS API
  description: |-
    API documentation for the SPAINEWS API.
  contact:
    email: antoniojosedonishung@gmail.com
  license:
    name: MIT
  version: 0.9.0

tags:
  - name: Authentication
    description: Authentication operations
  - name: News
    description: News query operations

paths:
  /register:
    put:
      tags:
        - Authentication
      summary: Requests a user registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                username: sulcud
                email: sulcud@mail.com
                password: my_password
      responses:
        '200':
          description: Registration request made successfully, user should verify his email.
        '500':
          $ref: "#/components/responses/server-error"
  /confirm/registration:
    post:
      tags:
        - Authentication
      summary: Confirm the registration using the code sent by email
      parameters:
        - in: header
          name: Confirm-Code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Registration confirmed
        '403':
          description: Permission denied
        '500':
          $ref: "#/components/responses/server-error"
  /session:
    get:
      summary: Request a valid session cookie
      tags:
        - Authentication
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    type: string
                example:
                  session: 1234abcd
        '403':
          description: Permission denied
        '500':
          $ref: "#/components/responses/server-error"
    delete:
      summary: destroys a session cookie
      tags:
        - Authentication
      security:
        - session-key: [ ]
      responses:
        '200':
          description: Session destroyed
        '500':
          $ref: "#/components/responses/server-error"
  /password:
    post:
      summary: Updates the user password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                old-password:
                  type: string
                new-password:
                  type: string
              example:
                old-password: password
                new-password: my-new-password
      tags:
        - Authentication
      security:
        - session-key: [ ]
      responses:
        '200':
          description: Password updated
        '403':
          description: Permission denied
        '500':
          $ref: "#/components/responses/server-error"
  /account:
    get:
      summary: Returns account information
      tags:
        - Authentication
      security:
        - session-key: [ ]
      responses:
        '200':
          description: Account information
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                  creation-date:
                    type: string
                    example: "31/12/2000"
        '403':
          description: Permission denied
        '500':
          $ref: "#/components/responses/server-error"
  /reset/password:
    post:
      summary: Requests a password reset, useful in case the user forgets its credentials. It sent an email to the account with the code that will be used to reset the credentials.
      tags:
        - Authentication
      security:
        - session-key: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Reset email sent
        '500':
          $ref: "#/components/responses/server-error"
  /email:
    post:
      summary: Requests an update for the email address. Send to the new email a confirmation URL / CODE
      tags:
        - Authentication
      security:
        - session-key: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                new-email:
                  type: string
      responses:
        '200':
          description: Confirmation email sent to new address
        '500':
          $ref: "#/components/responses/server-error"
  /confirm/email:
    post:
      summary: Ensures the new email provided if owned by the user
      tags:
        - Authentication
      security:
        - session-key: [ ]
      parameters:
        - in: header
          name: Confirm-Code
          description: Confirm code
          schema:
            type: string
      responses:
        '200':
          description: Email confirmed
        '500':
          $ref: "#/components/responses/server-error"
  /words:
    post:
      summary: Update words
      tags:
        - Authentication
      security:
        - session-key: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                automatic:
                  type: boolean
                words:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Words updated
        '500':
          $ref: "#/components/responses/server-error"
    get:
      summary: Return the configured key words for the current account.
      tags:
        - Authentication
      security:
        - session-key: [ ]
      responses:
        '200':
          description: Confirmation email sent to new address
          content:
            application/json:
              schema:
                type: object
                properties:
                  automatic:
                    type: boolean
                  words:
                    type: array
                    items:
                      type: string
        '500':
          $ref: "#/components/responses/server-error"
  /news/{page}:
    get:
      tags:
        - News
      summary: Requests the latest news obtained from the crawler.
      parameters:
        - in: path
          name: page
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Confirmation email sent to new address
          content:
            application/json:
              schema:
                type: object
                properties:
                  current-page:
                    type: integer
                  number-of-results:
                    type: integer
                  news:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        description:
                          type: string
                        maintext:
                          type: string
                        authors:
                          type: array
                          items:
                            type: string
                        category:
                          type: string
                        date_publish:
                          type: string
                        source_domain:
                          type: string
                        url:
                          type: string
        '500':
          $ref: "#/components/responses/server-error"
  /search/{page}:
    post:
      tags:
        - News
      summary: Requests the latest news obtained from the crawler.
      parameters:
        - in: path
          name: page
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start-date:
                  type: string
                  example: "31/12/2022"
                end-date:
                  type: string
                  example: "31/12/2022"
                sources:
                  type: array
                  items:
                    type: string
                maitext-word:
                  type: array
                  items:
                    type: string
                title-words:
                  type: array
                  items:
                    type: string
                old-first:
                  type: boolean

      responses:
        '200':
          description: Confirmation email sent to new address
          content:
            application/json:
              schema:
                type: object
                properties:
                  current-page:
                    type: integer
                  number-of-results:
                    type: integer
                  news:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        description:
                          type: string
                        maintext:
                          type: string
                        authors:
                          type: array
                          items:
                            type: string
                        category:
                          type: string
                        date_publish:
                          type: string
                        source_domain:
                          type: string
                        url:
                          type: string
        '500':
          $ref: "#/components/responses/server-error"