name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Prepare environment
        run: docker-compose -f ./compose-dev-databases.yaml up -d --build
      - name: Test
        run: go test -v ./...
